//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MrSparklyMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.SalesOrderLines = new HashSet<SalesOrderLine>();
        }
    
        public int productID { get; set; }
        public string productBrandName { get; set; }
        public Nullable<decimal> productCostPrice { get; set; }
        public Nullable<decimal> productRetailPrice { get; set; }
        public Nullable<short> productQty { get; set; }
    
        public virtual ICollection<SalesOrderLine> SalesOrderLines { get; set; }
    }
}
