//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MrSparklyMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrderLine
    {
        public int purchaseOrderLinesID { get; set; }
        public Nullable<int> purchaseOrderID { get; set; }
        public Nullable<int> rawMaterialsID { get; set; }
        public Nullable<short> purchaseOrderItemQty { get; set; }
        public Nullable<decimal> purchaseOrderItemPrice { get; set; }
        public Nullable<decimal> purchaseOrderLineSubtotal { get; set; }
    
        public virtual PurchaseOrder PurchaseOrder { get; set; }
        public virtual RawMaterial RawMaterial { get; set; }
    }
}
