//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MrSparklyMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RawMaterial
    {
        public RawMaterial()
        {
            this.PurchaseOrderLines = new HashSet<PurchaseOrderLine>();
        }
    
        public int rawMaterialsID { get; set; }
        public string rawMaterialsName { get; set; }
        public Nullable<decimal> rawMaterialsPrice { get; set; }
        public Nullable<short> rawMaterialsQty { get; set; }
    
        public virtual ICollection<PurchaseOrderLine> PurchaseOrderLines { get; set; }
    }
}
