//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MrSparklyMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Retailer
    {
        public Retailer()
        {
            this.SalesOrders = new HashSet<SalesOrder>();
        }
    
        public int retailerID { get; set; }
        public Nullable<int> employeeID { get; set; }
        public string retailerName { get; set; }
        public string retailerContactName { get; set; }
        public string retailerStreet { get; set; }
        public string retailerPhone { get; set; }
        public string retailerMob { get; set; }
        public string retailerFax { get; set; }
        public string retailerEmail { get; set; }
        public Nullable<int> suburbID { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Suburb Suburb { get; set; }
        public virtual ICollection<SalesOrder> SalesOrders { get; set; }
    }
}
