//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MrSparklyMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Suburb
    {
        public Suburb()
        {
            this.Employees = new HashSet<Employee>();
            this.Retailers = new HashSet<Retailer>();
            this.Suppliers = new HashSet<Supplier>();
        }
    
        public int suburbID { get; set; }
        public string suburb1 { get; set; }
        public string state { get; set; }
        public string zip { get; set; }
    
        public virtual ICollection<Employee> Employees { get; set; }
        public virtual ICollection<Retailer> Retailers { get; set; }
        public virtual ICollection<Supplier> Suppliers { get; set; }
    }
}
