//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MrSparklyWPF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.Retailers = new HashSet<Retailer>();
        }
    
        public int employeeID { get; set; }
        public string employeeFirstName { get; set; }
        public string employeeLastName { get; set; }
        public string employeeStreet { get; set; }
        public string employeePhone { get; set; }
        public string employeeMob { get; set; }
        public string employeeFax { get; set; }
        public string employeeEmail { get; set; }
        public string employeeDepartment { get; set; }
        public string employeeUsername { get; set; }
        public string employeePassword { get; set; }
        public Nullable<int> suburbID { get; set; }
    
        public virtual Suburb Suburb { get; set; }
        public virtual ICollection<Retailer> Retailers { get; set; }
    }
}
