//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MrSparklyWPF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesOrderLine
    {
        public int salesOrderLinesID { get; set; }
        public Nullable<int> salesOrderID { get; set; }
        public Nullable<int> productID { get; set; }
        public Nullable<short> salesOrderItemQty { get; set; }
        public Nullable<decimal> salesOrderItemPrice { get; set; }
        public Nullable<decimal> salesOrderLinesSubtotal { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual SalesOrder SalesOrder { get; set; }
    }
}
