//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MrSparklyWPF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesOrder
    {
        public SalesOrder()
        {
            this.SalesOrderLines = new HashSet<SalesOrderLine>();
        }
    
        public int salesOrderID { get; set; }
        public Nullable<int> retailerID { get; set; }
        public string salesOrderNo { get; set; }
        public Nullable<System.DateTime> salesOrderDate { get; set; }
    
        public virtual Retailer Retailer { get; set; }
        public virtual ICollection<SalesOrderLine> SalesOrderLines { get; set; }
    }
}
